server:
  port: 9803
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordersystem?userUnicode=true&characterEncoding=UTF-8
    username: root
    password: 981222
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server地址
        server-addr: localhost:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 2
      logic-not-delete-value: 0