server:
  port: 9801
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordersystem?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 981222
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server地址
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
#  打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 2
      logic-not-delete-value: 0
#  扫描枚举类
  type-enums-package: com.hsrxxx.enums.**