export { default as Main } from './Main'
export { default as Navbar } from './Navbar'
export { default as Sidebar } from './Sidebar'
// export { default as Settings } from './Settings'
// export { default as TagsView } from './TagsView/index.vue'
